%Your Implementation of Newton's method
%INPUTS:
%fun: the mathematical function for which we want to compute the root
% note that the output of fun may include the derivative
% i.e. [fval,dfdx] = fun(x)
% or not, i.e. fval = fun(x)
%x_guess the initial guess for Newton's method
%solver_params: a MATLAB struct containing solver settings
% solver_params.dxtol: terminate early if |x_{i+1}-x_{i}|<dxtol
% solver_params.ftol: terminate early if |f(x_i)|<ftol
% solver_params.dxmax: terminate early if |x_{i+1}-x_{i}|>dxmax
% (meaning that jacobian is probably singular, which is bad)
% solver_params.numerical_diff: boolean (0 or 1)
% 1-> numerically differentiate, 0-> use analytical derivative
%should use numerical differentation to compute the Jacobian or
%use a Jacobian generated by fun. No input assumes numerical by default
% true->fun is assumed to return [fval,J]
% false->fun is assumed to only return fval
%OUTPUTS:
%x: the estimate of the root computed by the function
% exit_flag: an integer indicating whether or not the solver succeeded
function [x, exit_flag] = multi_newton_solver(fun,x_guess,solver_params)
    %unpack values from struct (if fields in struct have been set)
    dxtol = 1e-14;
    if isfield(solver_params,'dxtol')
        dxtol = solver_params.dxtol;
    end
    ftol = 1e-14;
    if isfield(solver_params,'ftol')
        ftol = solver_params.ftol;
    end
    dxmax = 1e8;
    if isfield(solver_params,'dxmax')
        dxmax = solver_params.dxmax;
    end
    numerical_diff = 1;
    if isfield(solver_params,'numerical_diff')
        numerical_diff = solver_params.numerical_diff;
    end
    approximate_jacobian(fun, x_guess, dxtol, ftol, dxmax, numerical_diff)
    
    x_init = x_guess;

    % [fvals,dfdx] = fun(x_guess);

    J = approximate_jacobian(fun,x_guess)

    while abs(f) > ytol
        % Add break condition for 0 denominator
        inv_test = det(J*J');
        if inv_test < 1e-14
            disp('Matrix inverted, aborting...')
            break
        end
        % Run update step for Newton's Method
        x1 = x_init - J\f;
        
        % Check if difference is sufficiently small to consider a root found
        
        if abs(x1 - x_init) < dxtol
            x = x1;
            return
        end

        % Update x input for Newton's Method
        x_init = x1;

        % Re-evaluate function and derivative
        f = fun(x_init);
        J = approximate_jacobian(fun,x_init);
    end


    if abs(x_next - x_current) < 1e-14 && abs(fvals) < 1e-14
        x = x_current
    
    end
end